# Generated by Django 4.1.3 on 2022-11-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='home/img')),
            ],
        ),
    ]
