# Generated by Django 4.0.2 on 2022-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='title_type',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
