# Generated by Django 4.0.2 on 2022-11-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roses',
            name='sort',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
