# Generated by Django 4.0.2 on 2022-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_roses_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='roses',
            name='color',
            field=models.CharField(default='red', max_length=100),
        ),
        migrations.AddField(
            model_name='roses',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='roses',
            name='number_of_flowers',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='roses',
            name='size_flowers',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='roses',
            name='width',
            field=models.IntegerField(default=80),
        ),
    ]
