# Generated by Django 4.0.2 on 2022-11-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_roses_author_roses_city_made_roses_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roses',
            name='sort',
            field=models.CharField(default='Флорибунда', max_length=100),
        ),
    ]
