# Generated by Django 4.0.2 on 2022-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_roses_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='roses',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
